version: 0.2
phases:
  pre_build:
    commands:
      - git checkout develop
  build:
    commands:
      - composer install
artifacts:
  files:
    - '**/*'
  name: test-build-$(date +%Y-%m-%d)-$CODEBUILD_BUILD_ID
