version: 0.2
phases:
  pre_build:
    commands:
    # for independant build stage - git checkout develop
  build:
    commands:
      - cp .env.example .env
      - composer install
artifacts:
  files:
    - '**/*'
  name: test-build-$(date +%Y-%m-%d)-$CODEBUILD_BUILD_ID
